import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import { ThemeProvider } from "next-themes";
import StartBackground from "../StartBackground";
import { SanityLive } from "@/sanity/lib/live";
import { FloatingDock } from "@/components/FloatingDock";
import FloatingDockDemo from "@/components/ui/floating-dock-demo";
import { FloatingDock2 } from "@/components/ui/floating-dock-client2";
import { FloatingDockClient } from "@/components/FloatingDockClient";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning={true}>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					enableSystem={true}
					defaultTheme="system"
					attribute="class"
				>
					<StartBackground />
					{children}

					{/* <FloatingDock /> */}
					<FloatingDockDemo />
					{/* <FloatingDock2 items={[]} /> */}

					<SanityLive />
				</ThemeProvider>
			</body>
		</html>
	);
}
